name: Create Organization Profile README

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create profile directory
        run: mkdir -p profile
      - name: Copy README to profile
        run: cp README.md profile/README.md
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add profile/README.md
          git diff --cached --quiet && echo "No changes to commit" || git commit -m "docs: update organization profile README"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
